language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update --no-interaction --prefer-source

script: phpunit

matrix:
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION=dev-master
