language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.0.0
  - SYMFONY_VERSION=v2.0.1
  - SYMFONY_VERSION=v2.0.2
  - SYMFONY_VERSION=v2.0.3
  - SYMFONY_VERSION=v2.0.4
  - SYMFONY_VERSION=v2.0.5
  - SYMFONY_VERSION=v2.0.6
  - SYMFONY_VERSION=v2.0.7
  - SYMFONY_VERSION=v2.0.8
  - SYMFONY_VERSION=v2.0.9
  - SYMFONY_VERSION=v2.0.10
  - SYMFONY_VERSION=v2.0.11
  - SYMFONY_VERSION=v2.0.12
  - SYMFONY_VERSION=v2.0.13
  - SYMFONY_VERSION=v2.0.14
  - SYMFONY_VERSION=v2.0.15
  - SYMFONY_VERSION=v2.0.16

before_script: php vendor/vendors.php
